=== getappsh/api/common/src/env/env.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$defs": {
    "ScopeName": {
      "type": "string",
      "enum": [
        "general",
        "microservice",
        "api",
        "auth",
        "apm",
        "proxy",
        "postgres",
        "smtp",
        "cache",
        "S3",
        "jwt",
        "getMap",
        "libotEmu",
        "kafka",
        "cosign",
        "sbom"
      ]
    },
    "ScopeMappingObject": {
      "type": "object",
      "properties": {
        "id": {
          "$ref": "#/$defs/ScopeName"
        },
        "note": {
          "type": "string"
        }
      },
      "required": [
        "id"
      ],
      "additionalProperties": false
    },
    "ServicesMappingValue": {
      "type": "object",
      "properties": {
        "requiredScopes": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/ScopeMappingObject"
          }
        },
        "optionalScopes": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/ScopeMappingObject"
          }
        }
      },
      "additionalProperties": false
    },
    "Tag": {
      "type": "object",
      "required": [
        "name",
        "description"
      ],
      "properties": {
        "name": {
          "type": "string",
          "description": "Name of the tag, used in the code and documentation"
        },
        "description": {
          "type": "string",
          "description": "Description of the tag, used to describe the tag in the documentation"
        }
      },
      "additionalProperties": false
    },
    "ConditionObject": {
      "type": "object",
      "propertyNames": {
        "type": "string"
      },
      "additionalProperties": {
        "type": "string"
      },
      "minProperties": 1
    },
    "VariableRequiredCondition": {
      "oneOf": [
        {
          "type": "boolean"
        },
        {
          "type": "object",
          "oneOf": [
            {
              "properties": {
                "if": {
                  "$ref": "#/$defs/ConditionObject"
                }
              },
              "required": [
                "if"
              ],
              "additionalProperties": false
            },
            {
              "properties": {
                "oneOf": {
                  "type": "array",
                  "items": {
                    "$ref": "#/$defs/ConditionObject"
                  },
                  "minItems": 1
                }
              },
              "required": [
                "oneOf"
              ],
              "additionalProperties": false
            }
          ]
        }
      ]
    },
    "Variable": {
      "type": "object",
      "required": [
        "name",
        "description",
        "required",
        "type"
      ],
      "properties": {
        "name": {
          "type": "string",
          "description": "Name of the environment variable, used in the code and documentation"
        },
        "tag": {
          "type": "string",
          "description": "Optional tag for the variable, for a separate section in the documentation"
        },
        "description": {
          "type": "string",
          "description": "description of the environment variable, used to describing the var in the documentation"
        },
        "warning": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Optional warnings for the variable, to highlight important information in the documentation"
        },
        "notes": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Optional notes for the variable, to provide additional information in the documentation"
        },
        "required": {
          "$ref": "#/$defs/VariableRequiredCondition"
        },
        "format": {
          "type": "string",
          "description": "Optional format for the variable, to specify the expected format of the value (e.g., 'email', 'url', 'date')"
        },
        "pattern": {
          "type": "string",
          "description": "Optional regex pattern for the variable, to validate the value against a specific pattern"
        },
        "default": {},
        "example": {},
        "type": {
          "type": "string",
          "enum": [
            "number",
            "string",
            "boolean",
            "enum"
          ]
        },
        "enum": {
          "type": "array",
          "items": {
            "type": [
              "string",
              "number",
              "boolean"
            ]
          },
          "minItems": 1
        },
        "deprecated": {
          "type": "boolean",
          "description": "Indicates whether the variable is deprecated"
        },
        "deprecationNote": {
          "type": "string",
          "description": "Optional note explaining why the variable is deprecated or what to use instead"
        },
        "hidden": {
          "type": "boolean",
          "description": "Optional flag to hide the variable from documentation"
        }
      },
      "additionalProperties": false,
      "allOf": [
        {
          "if": {
            "properties": {
              "type": {
                "const": "enum"
              }
            }
          },
          "then": {
            "required": [
              "enum"
            ]
          },
          "else": {
            "not": {
              "required": [
                "enum"
              ]
            }
          }
        }
      ]
    }
  },
  "type": "object",
  "title": "Getapp-Environment, schema",
  "description": "Environment variables schema for getapp microservice.",
  "required": [
    "servicesMapping",
    "scopes"
  ],
  "additionalProperties": false,
  "properties": {
    "$schema": {
      "type": "string"
    },
    "title": {
      "type": "string"
    },
    "id": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "version": {
      "type": "string"
    },
    "servicesMapping": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#/$defs/ServicesMappingValue"
      }
    },
    "scopes": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "id",
          "title",
          "description",
          "variables"
        ],
        "additionalProperties": false,
        "properties": {
          "title": {
            "type": "string"
          },
          "id": {
            "$ref": "#/$defs/ScopeName"
          },
          "description": {
            "type": "string"
          },
          "tags": {
            "type": "array",
            "items": {
              "$ref": "#/$defs/Tag"
            }
          },
          "variables": {
            "type": "array",
            "items": {
              "$ref": "#/$defs/Variable"
            }
          }
        }
      }
    }
  }
}

=== getappsh/api/libs/common/src/env/env.json
{
    "$schema": "./env.schema.json",
    "title": "Get-App, Environment documentation",
    "id": "get-app",
    "description": "Environment variables documentation for get-app microservice.",
    "version": "1.0.0",
    "servicesMapping": {
      "api": {
        "requiredScopes": [
          {
            "id": "microservice"
          },
          {
            "id": "auth"
          }
        ],
        "optionalScopes": [
          {
            "id": "general"
          },
          {
            "id": "api"
          },
          {
            "id": "apm",
            "note": "Should be set in order to enable APM features"
          },
          {
            "id": "proxy",
            "note": "Required if the microservice is in a proxy mode"
          }
        ]
      },
      "discovery": {
        "requiredScopes": [
          {
            "id": "microservice"
          },
          {
            "id": "postgres"
          },
          {
            "id": "smtp",
            "note": "Required to enable the microservice sends emails"
          }
        ],
        "optionalScopes": [
          {
            "id": "general"
          },
          {
            "id": "apm",
            "note": "Should be set in order to enable APM features"
          }
        ]
      },
      "delivery": {
        "requiredScopes": [
          {
            "id": "microservice"
          },
          {
            "id": "postgres"
          },
          {
            "id": "S3"
          }
        ],
        "optionalScopes": [
          {
            "id": "general"
          },
          {
            "id": "apm",
            "note": "Should be set in order to enable APM features"
          },
          {
            "id": "cache",
            "note": "Required if the microservice is in a proxy mode or uses the delivery service as a cache layer"
          },
          {
            "id": "proxy",
            "note": "Required if the microservice is in a proxy mode"
          }
        ]
      },
      "offering": {
        "requiredScopes": [
          {
            "id": "microservice"
          },
          {
            "id": "postgres"
          },
          {
            "id": "apm"
          }
        ],
        "optionalScopes": [
          {
            "id": "general"
          }
        ]
      },
      "deploy": {
        "requiredScopes": [
          {
            "id": "microservice"
          },
          {
            "id": "postgres"
          }
        ],
        "optionalScopes": [
          {
            "id": "general"
          },
          {
            "id": "apm",
            "note": "Should be set in order to enable APM features"
          }
        ]
      },
      "project-management": {
        "requiredScopes": [
          {
            "id": "microservice"
          },
          {
            "id": "postgres"
          },
          {
            "id": "jwt"
          }
        ],
        "optionalScopes": [
          {
            "id": "general"
          },
          {
            "id": "apm",
            "note": "Should be set in order to enable APM features"
          }
        ]
      },
      "upload": {
        "requiredScopes": [
          {
            "id": "microservice"
          },
          {
            "id": "postgres"
          },
          {
            "id": "S3"
          },
          {
            "id": "cosign"
          }
        ],
        "optionalScopes": [
          {
            "id": "general"
          },
          {
            "id": "apm",
            "note": "Should be set in order to enable APM features"
          },
          {
            "id": "sbom",
            "note": "Required to enable SBOM scanning integration"
          }
        ]
      },
      "get-map": {
        "requiredScopes": [
          {
            "id": "microservice"
          },
          {
            "id": "postgres"
          },
          {
            "id": "getMap"
          }
        ],
        "optionalScopes": [
          {
            "id": "general"
          },
          {
            "id": "apm",
            "note": "Should be set in order to enable APM features"
          }
        ]
      },
      "libot-emu": {
        "requiredScopes": [
          {
            "id": "libotEmu"
          }
        ],
        "optionalScopes": []
      }
    },
    "scopes": [
      {
        "title": "General Configuration",
        "id": "general",
        "description": "General environment variables used for all microservices",
        "variables": [
          {
            "name": "RPC_PAYLOAD_VERSION",
            "description": "Version of the payload to send, default is 1.",
            "required": false,
            "type": "enum",
            "enum": [
              "1",
              "2"
            ],
            "warning": [
              "If implemented, it must be consistent across all microservices."
            ],
            "deprecated": true,
            "deprecationNote": "Type 1 of RPC_PAYLOAD_VERSION is deprecated and will be removed in the future, use only type 2.",
            "default": "1"
          },
          {
            "name": "REGION",
            "description": "Defines the region used for Kafka topics and database names. ",
            "warning": [
              "If implemented, it must be consistent across all microservices."
            ],
            "required": false,
            "type": "string"
          },
          {
            "name": "SERVER_NAME",
            "description": "Name of the server instance.",
            "warning": [
              "Should be unique within the deployment environment."
            ],
            "required": false,
            "type": "string"
          },
          {
            "name": "DEPLOY_ENV",
            "description": "Deployment environment identifier. Typical values: ORIGIN or PROXY.",
            "required": false,
            "type": "enum",
            "enum": [
              "CTS",
              "TNG",
              "ORIGIN",
              "PROXY"
            ],
            "hidden": true
          },
          {
            "name": "LOGGER_FORMAT",
            "description": "Format of the logs output by the microservice. Can be JSON or STRING.",
            "required": false,
            "type": "enum",
            "enum": [
              "JSON",
              "STRING"
            ],
            "default": "STRING",
            "tag": "Logger"
          },
          {
            "name": "LOG_LEVEL",
            "description": "Defines the logging level. For JSON logger: [\"fatal\", \"error\", \"warn\", \"info\", \"debug\", \"trace\"]. For STRING logger: [\"log\", \"error\", \"warn\", \"debug\", \"verbose\"].",
            "required": false,
            "type": "enum",
            "enum": [
              "fatal",
              "error",
              "warn",
              "info",
              "debug",
              "trace",
              "log",
              "verbose"
            ],
            "default": " \"trace\" or \"verbose\"",
            "tag": "Logger"
          }
        ]
      },
      {
        "title": "Microservice Client",
        "id": "microservice",
        "description": "Environment variables to setting the communication between the microservices.",
        "variables": [
          {
            "name": "MICRO_SERVICE_TYPE",
            "tag": "General config",
            "description": "Type of microservice client (e.g., KAFKA or SOCKET).",
            "required": true,
            "type": "enum",
            "enum": [
              "KAFKA",
              "SOCKET"
            ]
          },
          {
            "name": "MICROSERVICE_RESPONSE_WAIT_TIME",
            "tag": "General config",
            "description": "Time in milliseconds to wait for a microservice response.",
            "required": false,
            "type": "number",
            "default": 10000
          },
          {
            "name": "KAFKA_BROKER_URL",
            "tag": "Config using KAFKA type",
            "description": "URL of the Kafka broker.",
            "required": {
              "if": {
                "MICRO_SERVICE_TYPE": "KAFKA"
              }
            },
            "type": "string",
            "notes": [
              "It can be a string-array of url separated by commas, e.g., 'url1,url2,url3'."
            ],
            "example": "http://example1.com,http://example2.com,http://example3.com"
          },
          {
            "name": "KAFKAJS_NO_PARTITIONER_WARNING",
            "tag": "Config using KAFKA type",
            "description": "Disable KafkaJS partitioned warning. Set to 1 to disable the warning.",
            "required": false,
            "type": "number"
          },
          {
            "name": "CONSUME_CONCURRENT",
            "tag": "Config using KAFKA type",
            "description": "Number of Kafka partitions consumed concurrently.",
            "required": false,
            "type": "number",
            "default": 100
          },
          {
            "name": "KAFKA_SSL",
            "tag": "Config using KAFKA type with SSL",
            "description": "Flag if connection to Kafka is by SSL.",
            "required": false,
            "type": "boolean",
            "default": false,
            "warning": [
              "It will be implemented in the future, for now needs to define the 'DEPLOY_ENV' variable"
            ]
          },
          {
            "name": "KAFKA_PEM_PATH",
            "tag": "Config using KAFKA type with SSL",
            "description": "File system path to the CA certificate PEM file for SSL connection to Kafka.",
            "required": {
              "if": {
                "MICRO_SERVICE_TYPE": "KAFKA",
                "KAFKA_SSL": "true"
              }
            },
            "type": "string",
            "example": "/path/to/ca.pem"
          },
          {
